# Generated by Django 5.1.2 on 2024-11-08 10:39

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learning_Ideal_way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_Ideal_way', tinymce.models.HTMLField()),
            ],
        ),
    ]
