# Generated by Django 5.1.2 on 2024-11-15 08:14

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=150)),
                ('user_description', tinymce.models.HTMLField()),
            ],
        ),
    ]
