# Generated by Django 5.1.3 on 2024-11-28 08:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_committee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni_committee',
            old_name='main_title',
            new_name='batch_year',
        ),
        migrations.RemoveField(
            model_name='alumni_committee',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='alumni_committee',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='alumni_committee',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='alumni_committee',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='alumni_committee',
            name='text_content',
        ),
        migrations.AddField(
            model_name='alumni_committee',
            name='achievement',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni_committee',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni_committee',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alumni_committee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
