# Generated by Django 5.1.3 on 2024-11-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nontechingstaff',
            name='achievement',
            field=models.CharField(blank=True, default='No achievements yet', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nontechingstaff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='teachingstaff',
            name='achievement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teachingstaff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
