# Generated by Django 5.1.3 on 2024-11-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_nontechingstaff_achievement_nontechingstaff_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nontechingstaff',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nontechingstaff',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
