# Generated by Django 5.1.3 on 2024-11-27 04:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_nontechingstaff_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nontechingstaff',
            name='achievement',
            field=tinymce.models.HTMLField(blank=True, default='No achievements yet'),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='achievement',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
