# Generated by Django 5.1.2 on 2024-11-08 05:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_image', models.FileField(default=None, max_length=250, null=True, upload_to='principal_image/')),
                ('principal_message', tinymce.models.HTMLField()),
            ],
        ),
    ]
