# Generated by Django 5.1.2 on 2024-11-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
