# Generated by Django 5.1.2 on 2024-11-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_notice', '0002_rename_sub_title_schoolnotice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnotice',
            name='main_title',
            field=models.CharField(max_length=300),
        ),
    ]
