# Generated by Django 5.1.3 on 2024-11-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Committees',
            new_name='Comm',
        ),
    ]
