# Generated by Django 5.1.3 on 2024-11-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_rename_committees_comm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comm',
            old_name='name',
            new_name='committee_name',
        ),
    ]
