# Generated by Django 5.1.2 on 2024-11-08 11:23

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=300)),
                ('group', models.CharField(max_length=50)),
                ('divisions_description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCurri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_curriculum_description', tinymce.models.HTMLField()),
            ],
        ),
    ]
