# Generated by Django 5.1.2 on 2024-11-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniRegFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('father_or_husband_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('taluka', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('passed_out_from_class', models.CharField(max_length=50)),
                ('year_of_passing_out', models.CharField(max_length=50)),
                ('present_qualification', models.CharField(max_length=50)),
                ('present_designation', models.CharField(max_length=150)),
            ],
        ),
    ]
