# Generated by Django 5.1.2 on 2024-11-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_reg_form_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniregformdata',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='district',
            field=models.CharField(max_length=50, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='email_id',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='father_or_husband_name',
            field=models.CharField(max_length=50, verbose_name='Father/Husband Name'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='mobile_no',
            field=models.CharField(max_length=50, verbose_name='Mobile No (Whatsapp No)'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='passed_out_from_class',
            field=models.CharField(max_length=50, verbose_name='Passed Out from the class'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='present_designation',
            field=models.CharField(max_length=150, verbose_name='Present Designation '),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='present_qualification',
            field=models.CharField(max_length=50, verbose_name='Present Qualification'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='taluka',
            field=models.CharField(max_length=50, verbose_name='Taluka'),
        ),
        migrations.AlterField(
            model_name='alumniregformdata',
            name='year_of_passing_out',
            field=models.CharField(max_length=50, verbose_name='Year of Passing Out'),
        ),
    ]
