# Generated by Django 5.1.2 on 2024-11-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_reg_form_data', '0002_alter_alumniregformdata_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniregformdata',
            name='present_designation',
            field=models.CharField(max_length=150, verbose_name='Present Designation'),
        ),
    ]
