# Generated by Django 5.1.3 on 2024-12-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_committee', '0002_management_c_2016_2020_management_c_2020_onwards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('achievement', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Management_c_2016_2020',
        ),
        migrations.DeleteModel(
            name='Management_c_2020_onwards',
        ),
        migrations.DeleteModel(
            name='ManagementCommittee',
        ),
        migrations.DeleteModel(
            name='SchoolCommittee',
        ),
        migrations.AddField(
            model_name='committeemembers',
            name='committee_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='management_committee.governingbody'),
        ),
    ]
