# Generated by Django 5.1.3 on 2024-12-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_committee', '0003_committeemembers_governingbody_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemembers',
            old_name='committee_member',
            new_name='department',
        ),
    ]
