# Generated by Django 5.1.2 on 2024-11-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('president_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='president',
            name='prsident_img',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='president_Img/'),
        ),
    ]
