# Generated by Django 5.1.2 on 2024-11-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_form', '0003_admissionform_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
