# Generated by Django 5.1.2 on 2024-11-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_form', '0006_remove_admissionform_default_message_when_form_is_not_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='pdf',
            field=models.FileField(default='', upload_to='AdmissionForm/'),
        ),
    ]
