# Generated by Django 5.1.3 on 2024-12-04 16:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoolCommitteeChairpersonMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShoolCommitteeChairpersonMessage_img', models.FileField(default=None, max_length=300, null=True, upload_to='ShoolCommitteeChairpersonMessage_img/')),
                ('ShoolCommitteeChairpersonMessage_msg', tinymce.models.HTMLField()),
            ],
        ),
    ]
