# Generated by Django 5.1.2 on 2024-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='HomeSlider/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='HomeSlider/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='HomeSlider/')),
            ],
        ),
    ]
