# Generated by Django 5.1.2 on 2024-11-14 07:06

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_slider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('text_content', tinymce.models.HTMLField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='HomeBlog/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='HomeBlog/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='HomeBlog/')),
            ],
        ),
    ]
