# Generated by Django 5.1.2 on 2024-11-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_slider', '0002_homeblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeblog',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='homeblog',
            name='image3',
        ),
    ]
