# Generated by Django 5.1.3 on 2024-11-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
